# -*- coding: utf-8 -*-
"""Discipline code -> (hub Role, Hebrew discipline). Verbatim port of DISC_MAP in
docs/handoffs/project_base_points/.../reference/ribbon-base-points.jsx.

*** CONFIRM BEFORE SHIPPING ***
HUB_ROLES below is copied from the design handoff as a provisional list. The
README is explicit that it must be checked against the real EasyBIM Hub project
settings (Hub > Project Settings > Roles) and match Format's/ACC's role list
character-for-character, or assignee mapping will silently fail on import.
Do not edit this file to "correct" role names without checking the real hub
first — flagged again in pbp_ui.py where roles are surfaced to the user.

DISC_MAP's Hebrew (HEB_OPTIONS) side is similarly provisional/ported from the
design handoff, EXCEPT "TR" -> "תנועה" (Traffic), corrected 2026-08-19 per the
requester against their real project. Any OTHER code's Hebrew mapping here
is still unconfirmed against real hub settings.
"""

HEB_OPTIONS = ["אדריכלות", "קונסטרוקציה", "אינסטלציה", "חשמל", "מיזוג אוויר", "אדריכלות נוף", "תנועה", "כללי"]

DISC_MAP = {
    # local two-letter EasyBIM codes
    "AR": ("Architect", "אדריכלות"), "ARC": ("Architect", "אדריכלות"),
    "ST": ("Structural Engineer", "קונסטרוקציה"),
    "ME": ("Mechanical Engineer", "מיזוג אוויר"), "EL": ("Electrical Engineer", "חשמל"),
    "PL": ("Plumbing Engineer", "אינסטלציה"), "FP": ("Fire Safety", "כללי"),
    "SN": ("Sanitation", "אינסטלציה"), "LS": ("Landscape", "אדריכלות נוף"),
    "EV": ("Elevators", "כללי"), "AC": ("Accessibility", "כללי"), "SF": ("Safety", "כללי"),
    "TR": ("Traffic Engineer", "תנועה"), "QS": ("Quantity Surveyor", "כללי"),
    "IN": ("Interior Designer", "אדריכלות"), "CO": ("BIM Manager", "כללי"),
    "CE": ("Geotechnical Engineer", "קונסטרוקציה"), "SV": ("Surveyor", "כללי"),
    # ISO 19650 / BS 1192 originator letters
    "A": ("Architect", "אדריכלות"), "B": ("Construction Manager", "כללי"),
    "C": ("Geotechnical Engineer", "קונסטרוקציה"), "D": ("Plumbing Engineer", "אינסטלציה"),
    "E": ("Electrical Engineer", "חשמל"), "F": ("Project Manager", "כללי"),
    "G": ("Surveyor", "כללי"), "H": ("Mechanical Engineer", "מיזוג אוויר"),
    "I": ("Interior Designer", "אדריכלות"), "K": ("Client", "כללי"),
    "L": ("Landscape", "אדריכלות נוף"), "M": ("Mechanical Engineer", "מיזוג אוויר"),
    "P": ("Plumbing Engineer", "אינסטלציה"), "Q": ("Quantity Surveyor", "כללי"),
    "S": ("Structural Engineer", "קונסטרוקציה"), "T": ("Project Manager", "כללי"),
    "W": ("Construction Manager", "כללי"), "X": ("other", "כללי"),
    "Y": ("Fire Safety", "כללי"), "Z": ("BIM Manager", "כללי"),
}

# Fixed discipline codes offered in the Setup/Results "Disc" dropdown.
DISC_CODES = ["AR", "ST", "ME", "EL", "PL", "FP", "SN", "LS", "EV", "AC", "SF",
              "TR", "QS", "IN", "CO", "CE", "SV", "other"]

# Architecture discipline codes — a link with one of these is a reference model,
# never something that itself needs a Reference (AR) match. Keep in sync with
# reference/ribbon-base-points.jsx's AR_CODES / reference/ribbon-data.jsx samples.
AR_CODES = ["AR", "ARC", "ARCH", "A"]

# TODO(confirm-before-ship): verbatim from the design handoff's provisional
# list — confirm against EasyBIM Hub > Project Settings > Roles before this
# tool is used to export real ACC issues. See README "Discipline code -> Role
# -> Hebrew discipline mapping".
HUB_ROLES = ["3D Visualizer", "Accessibility", "Acoustical Advisor", "Agronomist", "Aluminium",
    "Architect", "BIM Manager", "Blast protection", "Client", "Communication",
    "Construction Manager", "Cranes & Gates", "Electrical Engineer", "Elevators",
    "Environmental Engineer", "Facade Designers", "Fire Safety", "Geotechnical Engineer",
    "Hydrologist", "Interior Designer", "Kitchens design", "Landscape", "Lighting Designer",
    "Mechanical Engineer", "other", "Plumbing Engineer", "Project Manager",
    "Quantity Surveyor", "Radiation", "Safety", "Sanitation", "Security",
    "Structural Engineer", "Surveyor", "Thermal advisor", "Traffic Engineer",
    "VDC Manager", "Waterproofing"]


def auto_role(code):
    return DISC_MAP.get(code, ("other", "כללי"))[0]


def auto_heb(code):
    return DISC_MAP.get(code, ("other", "כללי"))[1]


def guess_role(code, assignee_list):
    """Best-effort default Role/Company for a discipline code, preferring a
    match in the PROJECT'S OWN typed assignee list over the generic English
    DISC_MAP label. A hub that names its roles differently (custom or
    Hebrew role names, or simply not on the EasyBIM Hub) would otherwise
    silently get auto_role(code)'s irrelevant English guess written into
    real issues the user never reviewed. Returns "" (not a wrong guess) if
    the project has typed its own list but nothing in it matches."""
    if not assignee_list:
        return auto_role(code)
    candidates = (auto_role(code), auto_heb(code))
    by_lower = dict((x.lower(), x) for x in assignee_list)
    for c in candidates:
        if c and c.lower() in by_lower:
            return by_lower[c.lower()]
    return ""
